server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
spring:
  session:
    store-type: redis
    # session30天过期
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/ai_pictures_lib
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  profiles:
    active: local
knife4j:
  enable: true
  openapi:
    title: ai-pictures-lib官方文档
    email: 2499202708@qq.com
    concat: 陈卓杰
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.web.aipictureslib.controller
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false



